'use strict';
// tests for hash
// Generated by serverless-mocha-plugin

const mod         = require('../hash/handler.js');
const mochaPlugin = require('serverless-mocha-plugin');
const lambdaWrapper     = mochaPlugin.lambdaWrapper;
const expect      = mochaPlugin.chai.expect;

const liveFunction = {
  region: process.env.SERVERLESS_REGION,
  lambdaFunction: process.env.SERVERLESS_PROJECT + '-hash'
}
var wrapped;

describe('hash', () => {
  before(function (done) {
//  wrapped = lambdaWrapper.wrap(liveFunction); // Run the deployed lambda
    wrapped = lambdaWrapper.wrap(mod);

    done()
  });

  it('should return two identical hashes', (done) => {
    //runHandler(event, customContext, callback)
    wrapped.runHandler({
      body: 'url1=https%3A%2F%2Fraw.githubusercontent.com%2Fjenssegers%2Fimagehash%2Fmaster%2Ftests%2Fimages%2Fforest%2Fforest-high.jpg&url2=https%3A%2F%2Fraw.githubusercontent.com%2Fjenssegers%2Fimagehash%2Fmaster%2Ftests%2Fimages%2Fforest%2Fforest-copyright.jpg'
    }, {}, (err, response) => {
      console.log(err);
      console.log(response);
      done('no tests implemented');
    });
  });
});
