'use strict';
// Unit tests for Serverless
// Generated by Serverless UnitTestBoilerplate
var s
const path       = require('path'),
      chai       = require('chai'),
      should     = chai.should(),
      Serverless = require('serverless'),
      querystring = require('querystring');

describe('ServerlessProjectTest', function() {
  beforeEach(function(done) {
    this.timeout(0);

    s = new Serverless();

    s.init().then(function() {
      s.config.projectPath = __dirname + '/../';
      s.setProject(new s.classes.Project({
        stages: {
          dev: { regions: { 'ap-northeast-1': {} }}
        },
        variables: {
          project: 'serverless-project',
          stage: 'dev',
          region: 'ap-northeast-1'
        }
      }));

      s.getProject().setFunction(new s.classes.Function(
        {
          name:"hash",
          runtime:"nodejs4.3"
        },
        __dirname + '/../hash/s-function.json'));

      done();
    });

  });

  describe('hash', function() {
    it('should return two identical hashes', function() {
      const body = querystring.stringify({
        url1: 'https://mtyiu.github.io/serverless-image-hash/images/nasa.png',
        url2: 'https://mtyiu.github.io/serverless-image-hash/images/nasa.png'
      });
      return (
        s.getProject().getFunction('hash').run('dev', 'ap-northeast-1', { body : body })
        .then(result => {
          result.response.hashes[0].should.equal(result.response.hashes[1])
          result.response.diff.should.equal(0)
        })
      );
    });

    it('should return two different hashes', function() {
      const body = querystring.stringify({
        url1: 'https://mtyiu.github.io/serverless-image-hash/images/nasa.png',
        url2: 'https://mtyiu.github.io/serverless-image-hash/images/img_fjords.jpg'
      });
      return (
        s.getProject().getFunction('hash').run('dev', 'ap-northeast-1', { body : body })
        .then(result => {
          result.response.hashes[0].should.not.equal(result.response.hashes[1])
          result.response.diff.should.not.equal(0)
        })
      );
    });

    it('should return two similar hashes (diff < 0.1)', function() {
      const body = querystring.stringify({
        url1: 'https://mtyiu.github.io/serverless-image-hash/images/forest-high.jpg',
        url2: 'https://mtyiu.github.io/serverless-image-hash/images/forest-copyright.jpg'
      });
      return (
        s.getProject().getFunction('hash').run('dev', 'ap-northeast-1', { body : body })
        .then(result => {
          result.response.hashes[0].should.not.equal(result.response.hashes[1])
          result.response.diff.should.be.below(0.1)
        })
      );
    });
  });
});
